### ISSUE TITLE
How (de)compression works?

### ISSUE THREAD

**Issue by 8lall0** [stijnfrishert/liblsdj#30]
Hi, 
that's not an issue but i dunno where i can ask.

How decompression/compression works? I'm trying to port this library to golang and i'm not understanding very well the algorithm...

Thanks!

**Comment by stijnfrishert** [comment]
Hey @8lall0! No problem, you're welcome to ask. :) Everything can be found on the [wiki](http://littlesounddj.wikia.com/wiki/File_Management_Structure), but I was confused too at first.

LSDJ sav format (de)compression is basically [run-length encoding](https://en.wikipedia.org/wiki/Run-length_encoding) with some extra's, so I'd start with reading up on that if you're unfamiliar. The simple idea is as follows: every time you read a byte on decompression you write output the same byte, _except_ when you read`0xC0` or `0xE0`. In those cases you've encountered a "command", which tells you what to output. For example, reading `0xE0, 0xF1, N` means: output the default instrument (which is 16 bytes) N times. The specific rules can be found over on the wiki.

The hardest part about (de)compression is probably the block structure. Every 512 bytes in the .sav memory starting at `0x8000` is a block. When you run into `0xE0, N` that means: jump to block N and continue reading from there (so if N is 5 you continue reading from `0x9000`.

That's basically all there is to it!

**Comment by 8lall0** [comment]
Very nice, thanks!

Right now i achieved something that makes kinda sense, my uncompressed song is 32773 bytes (5 too much)...
I think it has something to do about blocks.

Starting from the lsdsng file, i saw this line of code:
`if (block1position)
	*currentBlockPosition = *block1position + (long)((byte - 1) * blockSize);
else
	*currentBlockPosition += blockSize;

if (rvio->seek(*currentBlockPosition, SEEK_SET, rvio->user_data) != 0)
	return lsdj_error_new(error, "could not seek to new block position");`

So here you basically, when you encounter 0xE0 and its successor (calling it N) doesn't match neither 0xF0, 0xF1 and 0xFF it's a block, so you seek inside the file from the beginning to 512 bytes (0x200) multiplied by N-1. Am i right?

**Comment by stijnfrishert** [comment]
Nice, sounds like you're on the right track! (De)compression is probably the part of liblsdj that took me the most time to get right. It's been a while I've tackled the topic, but if I remember everything correctly here's some more pointers (no pun intended):

> So here you basically, when you encounter 0xE0 and its successor (calling it N) doesn't match neither 0xF0, 0xF1 and 0xFF it's a block...

Yes! Oh and `0xE0, 0xE0` isn't also a special case.

> So you seek inside the file from the beginning to 512 bytes (0x200) multiplied by N-1. Am i right?

It's important to realise what "the beginning" is from where block memory is computed. In a .sav file that's 0x8000 (like the wiki says). In .lsdsng's that's byte 9 (because the first 9 are for the project name and version) as shown [here](http://littlesounddj.wikia.com/wiki/.lsdsng_File_Format).

In truth you shouldn't jump N - 1 but N. So `0xE0, 0x10` means a block at offset 0x200 * 0x10 = 0x2000 (512 * 16 = 8192). Weird part here is that bytes 0x8000 - 0x8200 in a .sav are counted as a block, even though they contain project meta data and aren't available for writing/reading. Because I'm passing 0x8200 as `block1position`, that formula says N - 1. I might as well have passed `0x8000` and just used N. I hope that makes sense.

Now, **the biggest issue with blocks** is that LSDManager doesn't follow the rules on the wiki. Any .lsdsng it exports, it just takes the corresponding blocks and puts them sequentially in the file starting at 0x09. So that means the `0xE0, N` commands don't make any sense, and you should just read blocks in sequentially. That's what that if statement in your code snippet is about. In the case of reading .lsdsng's I just pass a NULL to `block1position`. That basically means: disregard N and just move on to the next block instead of computing an offset.

I would love to see your code (yay for MIT), though I have zero experience with Golang, so I don't think I'd be of any help. :)

**Comment by 8lall0** [comment]
Hello and thanks for your time!

A couple of things:

- i made public my [repo](https://github.com/8lall0/liblsdj)

- i'm dealing with this:
`
    union
    {
        struct
        {
            unsigned char pulse1[LSDJ_BOOKMARK_POSITION_COUNT];
            unsigned char pulse2[LSDJ_BOOKMARK_POSITION_COUNT];
            unsigned char wave[LSDJ_BOOKMARK_POSITION_COUNT];
            unsigned char noise[LSDJ_BOOKMARK_POSITION_COUNT];
        };
        unsigned char channels[LSDJ_BOOKMARK_POSITION_COUNT][LSDJ_CHANNEL_COUNT];
    } bookmarks;
`
What's the structure byte per byte of the input regarding bookmarks? Golang doesn't have unions...

- What's the purpose of this line of code?

`
(chainAllocTable[i / 8] >> (i % 8)) & 1
`

I need to know because the way golang handles byte operations.

Thank you!

**Comment by stijnfrishert** [comment]
Yay! Looks neat!

> What's the structure byte per byte of the input regarding bookmarks? Golang doesn't have unions...

I believe they're stored as a two-dimensional array of 4x16 (16 bookmarks per channel). Support for bookmarks is fairly new, I've frankly yet to test whether this is completely correct.

> What's the purpose of this line of code?

Basically it's just going through the chain allocation table to see which chains are in use and which are not. Every bit is either 0 or 1 and tells you whether the chain is active. So I'm dividing i/8 because each every 8 chains I'm moving to the next chainAllocTable byte, and then I'm using module and bitshift to find the correct bit within that byte.

**Comment by 8lall0** [comment]
Ok, now i'm getting the right number when i "decompress" the song.

Now what's the flow to obtain the save file? I read those uncompressed data into a song structure and then...?

**Comment by stijnfrishert** [comment]
Obtain what save file? I'm afraid I don't really understand :/

**Comment by 8lall0** [comment]
Ops, sorry, you're right :P

Now i'm getting a correct (i think) decompressed song, it's 32768 bytes long and the RB check is fine.

Now to write this song to a sav file, what's the deal?

**Comment by stijnfrishert** [comment]
@8lall0 have you looked at the wiki? I'm frankly a bit too caught up in work to walk you through the entire process, but .sav is basically

1) First 0x8000 bytes is the working memory song uncompressed
2) 0x8000-0x8200 is meta data about all the projects
3) 0x8200+ is blocks for all the project data

**Comment by 8lall0** [comment]
Thank for your help!

I'll figure out, your hint is exactly what i needed :)

**Comment by stijnfrishert** [comment]
@8lall0 I am closing this issue as solved. If you have any more questions feel free to reach out again :)

**Comment by 8lall0** [comment]
Hi, after 4 years i got my hands on my library, and now it reads everything correctly, i'm even able to decompress the sav and re-compress it onto a new sav file, plus it parses it in a more explicit structure (since my primary goal is to use this library as "documentation" for the sav format, plus the easier cross-compiling feature of Go is a nice plus)

I'm writing here 'cause i'd like to ask you if you know the structure of the single instruments, since you use the _set_instrument_bits_ that's not so clear to me.

If you think i should open a new issue let me know :)

Thanks for your library and keep up!

**Comment by defensem3ch** [comment]
> I'm writing here 'cause i'd like to ask you if you know the structure of the single instruments, since you use the _set_instrument_bits_ that's not so clear to me and it's not mentioned inside the wiki of lsdj :D

Hello - It does seem to be mentioned in the wiki but is only valid for version 6.7.0 https://littlesounddj.fandom.com/wiki/.sav_structure#Instrument_Structure
I believe the instrument format changes between versions of LSDJ, so the library probably doesn't support this - if it did, it has certainly changed in later versions of LSDJ and the wiki is out of date.

**Comment by 8lall0** [comment]
Thank you @defensem3ch , i didn't see that!

Yeah, probably it has changed, but should be a good start to at least understand it, thank you again!
